# Generated by Django 5.0.6 on 2024-06-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_info',
            field=models.JSONField(null=True),
        ),
    ]
