# Generated by Django 5.0.6 on 2024-06-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('importer', 'Importer'), ('exporter', 'Exporter'), ('admin', 'Administrator'), ('accountant', 'Accountant'), ('finance_manager', 'Finance Manager'), ('compliance_officer', 'Compliance Officer')], default='None', max_length=20),
            preserve_default=False,
        ),
    ]
